/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superjava.UI;

import marytts.MaryInterface;
import marytts.util.data.audio.AudioPlayer;
import java.util.TimerTask;
import java.util.Timer;
import java.util.Random;
import jaco.mp3.player.MP3Player;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import marytts.exceptions.SynthesisException;
/**
 *
 * @author PJgummywormz
 */
public class FourDee extends javax.swing.JFrame {

    private MaryInterface marytts;
    private Random r;
    private Timer t;
    private TimerTask tt;
    private TimerTask tt2;
    private MP3Player player;

    
    private final String[] strs = {"Admonished!","Foolish Guac Bowl Merchant","Nimble Navigator",
    "Centipede","The Wall Just Got Ten Feet Higher", "Four Twenty Blaze It","dough gee","doot doot"
            ,"there it is", "take their coats", "low energy","Build the wall"
    };
    
    private final File[] files;
    private final String[] imgs;
    
    /**
     * Creates new form FourDee
     * @param mi
     */
    public FourDee(MaryInterface mi) {
        initComponents();
        marytts = mi;
        //ap = pa;
        r = new Random();
        File f1 = new File("../res/cantstump.mp3");
        File f2 = new File("../res/honk.mp3");
        File f3 = new File("../res/skull1.mp3");
        File f4 = new File("../res/skull2.mp3");
        files = new File[4];
        files[0] = f1;
        files[1] = f2;
        files[2] = f3;
        files[3] = f4;
        
        imgs = new String[4];
        
        imgs[0] = "../res/eggplant.png";
        imgs[1] = "../res/eggplant2.png";
        imgs[2] = "../res/eggplant3.png";
        imgs[3] = "../res/eggplant4.png";
        
        t = new Timer();
        
        tt = new TimerTask(){
        @Override
        public void run(){
           player = new MP3Player(files[r.nextInt(files.length-1)]);
           player.play();
           ImageIcon i = new ImageIcon(imgs[r.nextInt(imgs.length -1)]);
                imgIcon.setIcon(i);
                imgIcon.setSize(i.getIconWidth(), i.getIconHeight());
        }
        };
        
        tt2 = new TimerTask(){
        @Override
        public void run(){
            try {
                AudioInputStream audio = marytts.generateAudio(strs[r.nextInt(strs.length - 1)]);
                AudioPlayer ap = new AudioPlayer();
                ap.setAudio(audio);
                ap.start();
                ap.join();
                
                
            } catch (SynthesisException ex) {
                Logger.getLogger(FourDee.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(FourDee.class.getName()).log(Level.SEVERE, null, ex);
            }
            //catch(IllegalStateException exx){System.out.println("why");}
        }
        };
        
        t.schedule(tt,800,800);
        t.schedule(tt2,10,5000);
        
        
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("I will host your slaves");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        t.cancel();
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FourDee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FourDee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FourDee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FourDee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FourDee(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgIcon;
    // End of variables declaration//GEN-END:variables
}
