/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superjava.UI;

import java.util.TimerTask;
import java.util.Timer;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Random;

/**
 *
 * @author PJgummywormz
 */
public class LiberalTolerance extends javax.swing.JFrame {

    
    private Timer t;
    private TimerTask tt;
    private Random r;
    private TimerTask tt2;
    
    private int baseX;
    private int baseY;
    private int vel;
    private boolean whereGo;
    private Dimension dim;
    private final String s;
    /**
     * Creates new form LiberalTolerance
     * @param bX - base x
     * @param bY - base y
     * @param lOrR
     */
    public LiberalTolerance(int bX, int bY, boolean lOrR,String s) {
        initComponents();
        baseX = bX;
        baseY = bY;
        whereGo = lOrR;
        
        if(lOrR){vel = 1;}
        else{vel = -1;}
        
        libTol.setText(s);
        
        dim = Toolkit.getDefaultToolkit().getScreenSize();
        t = new Timer();
        r = new Random();
        tt = new TimerTask(){
        @Override
        public void run(){
            libTol.setForeground(new Color(r.nextInt(255),r.nextInt(255),r.nextInt(255)));
        }
        };
        
        tt2 = new TimerTask(){
        @Override
        public void run(){
            moveMe();
        }
        };
        this.s = s;
        
    }

    public void moveMe()
    {
    if (this.getX() > dim.width - this.getWidth() && vel == 1){vel = -1;}
    else if (this.getX() <= 0 && vel == -1){vel = 1;}
    
    setLocation(this.getX() + (vel * 10),this.getY());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        libTol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        libTol.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        libTol.setText("LIBERAL TOLERANCE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(libTol)
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(libTol)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        t.schedule(tt,1000,1000);
        
        if(whereGo){setLocation(baseX-400,baseY);}
        else{setLocation(baseX+400,baseY);}
        t.schedule(tt2,50,50);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LiberalTolerance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LiberalTolerance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LiberalTolerance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LiberalTolerance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LiberalTolerance(0,0,true,"LIBERAL TOLERANCE").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel libTol;
    // End of variables declaration//GEN-END:variables
}
