/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superjava.UI;

/**
 *
 * @author PJgummywormz
 */
public class VictumBux extends javax.swing.JFrame {

    /**
     * Creates new form VictumBux
     */
    public VictumBux() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        results = new javax.swing.JDialog();
        twatter = new javax.swing.JLabel();
        patreon = new javax.swing.JLabel();
        horsemint = new javax.swing.JLabel();
        doneBtn = new javax.swing.JButton();
        calcThat = new javax.swing.JButton();
        genderBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        raceBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        sexBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        memeBox = new javax.swing.JComboBox<>();

        results.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        results.setTitle("Donate to my Patreon");
        results.setResizable(false);
        results.setSize(new java.awt.Dimension(400, 128));

        twatter.setText("jLabel5");

        patreon.setText("jLabel6");

        horsemint.setText("jLabel7");

        doneBtn.setText("kk");
        doneBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doneBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout resultsLayout = new javax.swing.GroupLayout(results.getContentPane());
        results.getContentPane().setLayout(resultsLayout);
        resultsLayout.setHorizontalGroup(
            resultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(twatter)
                    .addComponent(patreon)
                    .addComponent(horsemint))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultsLayout.createSequentialGroup()
                .addContainerGap(347, Short.MAX_VALUE)
                .addComponent(doneBtn)
                .addContainerGap())
        );
        resultsLayout.setVerticalGroup(
            resultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(twatter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patreon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(horsemint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(doneBtn)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Donate to my Patreon");
        setResizable(false);

        calcThat.setText("Calculate");
        calcThat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcThatMouseClicked(evt);
            }
        });

        genderBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "TumblrGender", "MemeGender" }));

        jLabel1.setText("Gender:");

        raceBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Black", "White", "Hispanic", "Mr. Skeltal", "TumblrEthnicity" }));

        jLabel2.setText("Ethnicity:");

        sexBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HeteroSexual", "Bisexual", "Weirdo", "TumblrGender", "VeganSexual" }));

        jLabel3.setText("Sexual Orientation:");

        jLabel4.setText("Meme Orientation:");

        memeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Illuminati", "Pepe", "Doge", "Swiggity Swooty", "420" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 303, Short.MAX_VALUE)
                        .addComponent(calcThat))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(memeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sexBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(raceBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(genderBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(raceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(memeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(calcThat)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcThatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcThatMouseClicked
        long score = 0;
        
        if(genderBox.getSelectedIndex() == 0){score-=980;}
        if(genderBox.getSelectedIndex() == 1){score += 50000;}
        if(genderBox.getSelectedIndex() == 2){score += 900000000;}
        if(genderBox.getSelectedIndex() == 3){score+=25;}
        
        if(raceBox.getSelectedIndex() == 0){score+=50000;}
        if(raceBox.getSelectedIndex() == 1){score-=900000;}
        if(raceBox.getSelectedIndex() == 2){score+=8000;}
        if(raceBox.getSelectedIndex() == 3){score += 666666;}
        if(raceBox.getSelectedIndex() == 4){score+= 98756444;}
        
        if(sexBox.getSelectedIndex() == 0){score-=8888888;}
        if(sexBox.getSelectedIndex() == 1){score += 25;}
        if(sexBox.getSelectedIndex() == 2){score += 58888;}
        if(sexBox.getSelectedIndex() == 3){score+=99999999;}
        if(sexBox.getSelectedIndex() == 4){score-= 984;}
        
        if(memeBox.getSelectedIndex() == 0){score+=580;}
        if(memeBox.getSelectedIndex() == 1){score += 864;}
        if(memeBox.getSelectedIndex() == 2){score -= 9998;}
        if(memeBox.getSelectedIndex() == 3){score-=9999999;}
        if(memeBox.getSelectedIndex() == 4){score-= 683;}
        
        long twit = (score / 640);
        long patreonx = (score / 1800);
        long horsemints = (score / 6000);
        
        if(twit < 0){ twit *= -1;}
        if(patreonx < 0){ patreonx *= -1;}
        if(horsemints < 0){ horsemints *= -1;}
        patreon.setText("Patreon Money Per Month: " + patreonx);
        twatter.setText("Number of Twitter Followers: " + twit);
        horsemint.setText("Number of Anti-Harassment Companies Founded: " + horsemints);
        results.setVisible(true);
        
    }//GEN-LAST:event_calcThatMouseClicked

    private void doneBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneBtnMouseClicked
        results.dispose();
    }//GEN-LAST:event_doneBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VictumBux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VictumBux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VictumBux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VictumBux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VictumBux().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcThat;
    private javax.swing.JButton doneBtn;
    private javax.swing.JComboBox<String> genderBox;
    private javax.swing.JLabel horsemint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> memeBox;
    private javax.swing.JLabel patreon;
    private javax.swing.JComboBox<String> raceBox;
    private javax.swing.JDialog results;
    private javax.swing.JComboBox<String> sexBox;
    private javax.swing.JLabel twatter;
    // End of variables declaration//GEN-END:variables
}
